python ~/scripts/run_train.py \
	--name="anisonet_default" \
	--train_file="dataset/train.p" \
	--em_dim="48" \
	--layers="2" \
	--lmax="3" \
	--num_basis="15" \
	--lr="0.003" \
	--wd="0.03" \
	--batch­_size="12" \
	--max_epoch="120" \
	--enable_progress_bar="True" \
